//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OREntities : DbContext
    {
        public OREntities()
            : base("name=OREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIAKOK> DIAKOKs { get; set; }
        public virtual DbSet<KAROK> KAROKs { get; set; }
        public virtual DbSet<KERDESEK> KERDESEKs { get; set; }
        public virtual DbSet<KERDOIVEK> KERDOIVEKs { get; set; }
        public virtual DbSet<SZAKOK> SZAKOKs { get; set; }
        public virtual DbSet<TANAROK> TANAROKs { get; set; }
        public virtual DbSet<TANSZEKEK> TANSZEKEKs { get; set; }
        public virtual DbSet<TANTARGYAK> TANTARGYAKs { get; set; }
        public virtual DbSet<VALASZOK> VALASZOKs { get; set; }
        public virtual DbSet<X> X { get; set; }
        public virtual DbSet<KERDES_VALASZLEHETOSEG> KERDES_VALASZLEHETOSEG { get; set; }
        public virtual DbSet<KERDOIV_KERDES> KERDOIV_KERDES { get; set; }
    }
}
