//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAKOK
    {
        public int ID_DIAKOK { get; set; }
        public string AZONOSITO { get; set; }
        public Nullable<int> ID_SZAKOK { get; set; }
        public Nullable<byte> EVFOLYAM { get; set; }
        public Nullable<bool> KITOLTOTTE1 { get; set; }
        public Nullable<bool> KITOLTOTTE2 { get; set; }
    
        public virtual SZAKOK SZAKOK { get; set; }
    }
}
