//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KAROK
    {
        public KAROK()
        {
            this.SZAKOKs = new HashSet<SZAKOK>();
            this.TANSZEKEKs = new HashSet<TANSZEKEK>();
        }
    
        public string NEV { get; set; }
        public int ID_KAROK { get; set; }
    
        public virtual ICollection<SZAKOK> SZAKOKs { get; set; }
        public virtual ICollection<TANSZEKEK> TANSZEKEKs { get; set; }
    }
}
