//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KERDOIVEK
    {
        public KERDOIVEK()
        {
            this.KERDOIV_KERDES = new HashSet<KERDOIV_KERDES>();
        }
    
        public int ID_KERDOIVEK { get; set; }
        public Nullable<int> ID_X { get; set; }
        public Nullable<bool> FELEV { get; set; }
        public Nullable<short> EV { get; set; }
    
        public virtual ICollection<KERDOIV_KERDES> KERDOIV_KERDES { get; set; }
    }
}
