//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KERDESEK
    {
        public KERDESEK()
        {
            this.KERDES_VALASZLEHETOSEG = new HashSet<KERDES_VALASZLEHETOSEG>();
            this.KERDOIV_KERDES = new HashSet<KERDOIV_KERDES>();
            this.VALASZOKs = new HashSet<VALASZOK>();
        }
    
        public int ID_KERDESEK { get; set; }
        public string KERDES { get; set; }
        public string TIPUS { get; set; }
    
        public virtual ICollection<KERDES_VALASZLEHETOSEG> KERDES_VALASZLEHETOSEG { get; set; }
        public virtual ICollection<KERDOIV_KERDES> KERDOIV_KERDES { get; set; }
        public virtual ICollection<VALASZOK> VALASZOKs { get; set; }
    }
}
