//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class KERDOIV_KERDES
    {
        public int ID_KERDOIV_KERDES { get; set; }
        public Nullable<int> ID_KERDOIV { get; set; }
        public Nullable<int> ID_KERDES { get; set; }
    
        public virtual KERDESEK KERDESEK { get; set; }
        public virtual KERDOIVEK KERDOIVEK { get; set; }
    }
}
