//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SZAKOK
    {
        public SZAKOK()
        {
            this.DIAKOKs = new HashSet<DIAKOK>();
            this.TANTARGYAKs = new HashSet<TANTARGYAK>();
            this.X = new HashSet<X>();
        }
    
        public int ID_SZAKOK { get; set; }
        public string NEV { get; set; }
        public System.DateTime IDOTARTAM { get; set; }
        public Nullable<int> ID_KAROK { get; set; }
    
        public virtual ICollection<DIAKOK> DIAKOKs { get; set; }
        public virtual KAROK KAROK { get; set; }
        public virtual ICollection<TANTARGYAK> TANTARGYAKs { get; set; }
        public virtual ICollection<X> X { get; set; }
    }
}
