//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TANAROK
    {
        public TANAROK()
        {
            this.X = new HashSet<X>();
        }
    
        public string NEV { get; set; }
        public int ID_TANAROK { get; set; }
        public string TANAROK_ALIAS { get; set; }
        public string JELSZO { get; set; }
        public string FUNKCIO { get; set; }
        public Nullable<int> ID_TANSZEKEK { get; set; }
        public string FELHASZNALO_TIPUSA { get; set; }
    
        public virtual TANSZEKEK TANSZEKEK { get; set; }
        public virtual ICollection<X> X { get; set; }
    }
}
