//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TANTARGYAK
    {
        public TANTARGYAK()
        {
            this.X = new HashSet<X>();
        }
    
        public int ID_TANTARGYAK { get; set; }
        public string NEV { get; set; }
        public string TIPUS { get; set; }
        public Nullable<int> ID_SZAKOK { get; set; }
    
        public virtual SZAKOK SZAKOK { get; set; }
        public virtual ICollection<X> X { get; set; }
    }
}
