//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class X
    {
        public int ID_X { get; set; }
        public Nullable<int> ID_TANAROK { get; set; }
        public Nullable<int> ID_TANTARGYAK { get; set; }
        public Nullable<int> ID_SZAKOK { get; set; }
        public Nullable<byte> EVFOLYAM { get; set; }
        public Nullable<bool> FELEV { get; set; }
        public string TANTARGY_TIPUS { get; set; }
    
        public virtual SZAKOK SZAKOK { get; set; }
        public virtual TANAROK TANAROK { get; set; }
        public virtual TANTARGYAK TANTARGYAK { get; set; }
    }
}
